export const SEARCH_FILTER = {
	SEARCH_REQUEST: 'SEARCH_REQUEST',
	SEARCH_SUCCESS: 'SEARCH_SUCCESS',
	SEARCH_FAILURE: 'SEARCH_FAILURE'
}

export const API = {
	BASE_URL: 'http://www.omdbapi.com',
	API_KEY: '78bff41d'
}

export const MOVIE = {
	GET_MOVIE_INFO_REQUEST: 'GET_MOVIE_INFO_REQUEST',
	GET_MOVIE_INFO_SUCCESS: 'GET_MOVIE_INFO_SUCCESS',
	GET_MOVIE_INFO_FAILURE: 'GET_MOVIE_INFO_FAILURE'
}